name: Application JVM
on: [workflow_dispatch]

jobs:
  Create-application-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Prepare Gradle
        run: chmod +x gradlew
        shell: bash
      - name: Build and push Docker image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :application:jib
            -DjibConfiguration=JVM
            -Djib.from.auth.username=${{ github.actor }}
            -Djib.from.auth.password=${{ secrets.GITHUB_TOKEN }}
            -Djib.to.auth.username=${{ github.actor }}
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
