name: Application
on: [workflow_dispatch]

jobs:
  Create-application-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Build and push Docker image
        run: |
          chmod +x gradlew
          ./gradlew jib \
            -Djib.from.auth.username=${{ github.actor }} \
            -Djib.from.auth.password=${{ secrets.GITHUB_TOKEN }} \
            -Djib.to.auth.username=${{ github.actor }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
        shell: bash
