name: Generator
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  Create-generator-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Prepare Gradle
        run: chmod +x gradlew
        shell: bash
      - name: Build and push Docker image
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :generator:jib
            -Djib.to.auth.username=${{ github.actor }}
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
